[package]
name = "1ntort/signal"
description = "Basic implementation of the classic 'signal' module."
version = "1.0.2"
authors = ["1ntort <>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
